openapi: 3.0.3
info:
  title: Morty Function Registry - API Documentation
  description: |-
    This document aims to provide a simple and clear Morty Function Registry endpoints documentation.
  version: 1.0.0
externalDocs:
  description: Morty Function Registry on Github.
  url: https://github.com/polyxia-org/morty-registry
tags:
  - name: Functions
    description: Functions API endpoints
paths:
  /v1/functions/build:
    post:
      tags:
        - Functions
      summary: Build a function and push the image into the registry.
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BuildRequest'
      responses:
        '200':
          description: The function build was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildResponse'
  /v1/functions/{id}/upload-link:
    get:
      parameters: 
        - name: id
          in: path
          description: The identifier of the function to upload.
          required: true
          schema:
            type: string
      tags:
        - Functions
      summary: Get an upload link to upload the function code into the underlying storage.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadLinkResponse'
        '500':
          description: An internal server error ocurred. Please check the logs of your registry for more details.
components:
  schemas:
    BuildRequest:
      type: object
      properties:
        runtime:
          type: string
          description: The name of the runtime to use.
          example: python-3
        name:
          type: string
          description: The name of the function.
          example: my-python-func
        code:
          type: string
          format: binary
    BuildResponse:
      type: object
      properties:
        imageUrl:
          type: string
          description: The URL of the function image.
    UploadLinkResponse:
      type: object
      properties:
        httpMethod:
          type: string
          example: "PUT"
        uploadLink:
          type: string

